
stands:
  blm:
    provider_name: Bureau of Land Management
    provider_url: https://gbp-blm-egis.hub.arcgis.com/datasets/blm-or-forest-operations-inventory-vegetation-publication-hub/about
    provider_roles: [licensor, producer, processor, host]
    description: > 
      This collection represent polygons from the BLM FOIVEG_POLY feature class, a detailed classification 
      of vegetation that covers forested lands and non-forest lands with broad and general classifications. 
      It includes related table data from the MicroStorms (MS) system to describe forest vegetation and delineates 
      polygons primarily based on differences in vegetative cover, size, and age. FOIVEG_POLY attributes describe 
      both the overall forest stand as well as the layers within that stand, including cover roles and ten-year age class.
    label_type: vector
    label_properties: 
    label_description: 
    label_task: regression
    label_name: BLM Forest Operations Inventory Vegetation
    label_license: 
      type:
      url: 

  dnr: 
    provider_name: Washington Department of Natural Resources
    provider_url: https://gis.dnr.wa.gov/site2/rest/services/Public_Forest_Mgmt/WADNR_PUBLIC_RS_FRIS/MapServer
    provider_roles: [licensor, producer, processor, host]
    description: > 
      RS-FRIS is a remote-sensing based forest inventory for WA DNR State Trust lands. RS-FRIS predicts forest 
      conditions using statistical models that relate field measurements to three-dimensional remotely-sensed data 
      (PhoDAR and LiDAR point clouds). Forest metrics are predicted at a scale of 1/10th acre and stored as rasters. 
    label_description: 
    label_type: vector
    label_properties: 
    label_task: regression
    label_name: WA DNR Remotely Sensed Forest Resource Inventory (RS-FRIS) 
    label_license: 
      type: propietary
      url: https://gis.dnr.wa.gov/portal/home/item.html?id=563d71c13dc644fa9c9d0f73916c637f
    # collection: RS_FRIS

items:
  3dep:
    description: > 
      The USGS 3D Elevation Program (3DEP) Bare Earth DEM Dynamic service is based on multi-resolution USGS DEM 
      sources and provides dynamic functions for visualization. These functions include: Hillshade, Aspect Map, 
      Hillshade Stretched, Multi-directional Hillshade, Slope Map, Elevation Tinted Hillshade, Contour. In addition 
      the OGC Web Map Service (WMS) and Web Coverage Service (WCS) interfaces are enabled. Data available in this 
      map service reflects all 3DEP DEM data published as of May 15, 2023.
    providers:
      USGS:
        name: USGS 3D Elevation Program (3DEP)
        type: [licensor, producer, processor, host]
        api: https://elevation.nationalmap.gov/arcgis/rest/services/3DEPElevation/ImageServer/exportImage
        url: https://www.usgs.gov/3d-elevation-program
        # collection: WA_NAIP_2021_9586
    license: 
      type: propietary
      url: https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits

  gflandsat:
    description: > 
      The Gap Filled Landsat (GFL) product is a 30m resolution, cloud-free, annual composite of Landsat 5, 7, and 8
      surface reflectance data. The GFL product is generated using the Google Earth Engine (GEE) platform and is
      available as a public GEE catalog. The GFL product is described in Kennedy et al. (2019). 
    providers:
      Google:
        name: Google Earth Engine
        roles: [host]
        api: https://earthengine-highvolume.googleapis.com
        url: https://developers.google.com/earth-engine/tutorials/community/histarfm-cloud-and-gap-free-landsat
        # collection: projects/KalmanGFwork/GFLandsat_V1
    license: 
      type: various
      url:

  landtrendr:
    description: >
        LandTrendr is a time series processing algorithm designed to detect and characterize temporal trajectories
        in Landsat pixel stacks. It is a linear spectral mixture model that uses a Kalman filter to identify
        abrupt and gradual changes in spectral trajectories. The algorithm is designed to be scalable and
        applicable to large time series stacks. It is implemented in Google Earth Engine (GEE) and is available
        as a public GEE application. The algorithm is described in Kennedy et al. (2010) and Kennedy et al. (2012).
        The GEE implementation is described in Kennedy et al. (2018).
    providers:
      Google:
        name: Google Earth Engine
        roles: [host]
        api: https://earthengine.googleapis.com
        url: https://emapr.github.io/LT-GEE/introduction.html
        # collection: projects/USFS/LT-GEE
    license: 
      type: various
      url:

  naip:
    description: > 
      The National Agriculture Imagery Program (NAIP), administered by the USDA's Farm Service Agency (FSA), acquires 
      aerial imagery during the agricultural growing seasons in the continental U.S. The NAIP provides 1-meter or better 
      resolution in an orthorectified format. 

      This collection contains NAIP imagery for Oregon and Washington available as 7.5-minute quarter quadrangle, 4-band 
      (RGBN) COG GeoTIFFs. 
    providers:
      Google:
        name: Google Earth Engine
        roles: [host] 
        api: https://earthengine-highvolume.googleapis.com
        url: https://developers.google.com/earth-engine/datasets/catalog/USDA_NAIP_DOQQ 
        # collection: USDA/NAIP/DOQQ
      NOAA:
        name: NOAA Digital Coast
        roles: [host]
        api: 
        url: https://coast.noaa.gov/htdata/raster5/imagery/WA_NAIP_2021_9586/
        # collection: WA_NAIP_2021_9586
      USDA:
        name: USDA Farm Production and Conservation - Business Center, Geospatial Enterprise Operations
        roles: [licensor, producer]
        url: https://naip-usdaonline.hub.arcgis.com/
    license: 
      type: propietary
      url: https://developers.google.com/earth-engine/datasets/catalog/USDA_NAIP_DOQQ#terms-of-use


# {"href": "https://developers.google.com/earth-engine/datasets/catalog/USDA_NAIP_DOQQ#terms-of-use", "rel": "license", "type": "text/html"}